-- Esquema para PostgreSQL. Execute no banco que deseja usar.

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_uid UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  nome_de_usuario VARCHAR(60) NOT NULL UNIQUE,
  tipo_de_perfil VARCHAR(10) NOT NULL DEFAULT 'operador'
    CHECK (tipo_de_perfil IN ('operador', 'gerente')),
  data_de_criacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS veiculos (
  id_veiculo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nome_modelo VARCHAR(60) NOT NULL,
  placa VARCHAR(10) NOT NULL UNIQUE,
  pressao_minima_psi NUMERIC(5,1) NOT NULL,
  pressao_maxima_psi NUMERIC(5,1) NOT NULL,
  situacao VARCHAR(10) NOT NULL DEFAULT 'liberado'
    CHECK (situacao IN ('liberado', 'bloqueado')),
  data_de_criacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT verificar_faixa_de_pressao
    CHECK (pressao_minima_psi < pressao_maxima_psi)
);

CREATE TABLE IF NOT EXISTS inspecoes (
  id_inspecao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_veiculo BIGINT NOT NULL REFERENCES veiculos(id_veiculo),
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario),
  data_da_inspecao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resultado VARCHAR(10) NOT NULL
    CHECK (resultado IN ('regular', 'irregular', 'pendente')),
  veiculo_bloqueado BOOLEAN NOT NULL DEFAULT FALSE,
  observacoes TEXT
);

CREATE TABLE IF NOT EXISTS itens_inspecao (
  id_item_inspecao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inspecao BIGINT NOT NULL REFERENCES inspecoes(id_inspecao)
    ON DELETE CASCADE,
  categoria VARCHAR(40) NOT NULL,
  nome_item VARCHAR(150) NOT NULL,
  valor VARCHAR(100),
  resultado VARCHAR(10) NOT NULL DEFAULT 'pendente'
    CHECK (resultado IN ('regular', 'irregular', 'pendente')),
  item_critico BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS indice_inspecoes_data
  ON inspecoes (data_da_inspecao);
CREATE INDEX IF NOT EXISTS indice_inspecoes_veiculo
  ON inspecoes (id_veiculo);
CREATE INDEX IF NOT EXISTS indice_itens_categoria
  ON itens_inspecao (categoria);
CREATE INDEX IF NOT EXISTS indice_itens_resultado
  ON itens_inspecao (resultado);

-- O Supabase Auth guarda as senhas; a tabela usuarios guarda apenas o perfil.
-- Esta migração também adapta uma instalação criada pela versão anterior deste arquivo.
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS auth_uid UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE usuarios DROP COLUMN IF EXISTS senha_criptografada;
CREATE UNIQUE INDEX IF NOT EXISTS indice_usuarios_auth_uid ON usuarios (auth_uid);

CREATE OR REPLACE FUNCTION criar_perfil_de_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.usuarios (auth_uid, nome_de_usuario, tipo_de_perfil)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'nome_de_usuario', split_part(NEW.email, '@', 1)),
    'operador'
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ao_criar_usuario_auth ON auth.users;
CREATE TRIGGER ao_criar_usuario_auth
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION criar_perfil_de_usuario();

CREATE OR REPLACE FUNCTION alterar_situacao_veiculo(codigo_veiculo VARCHAR, nova_situacao VARCHAR)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'É necessário entrar no sistema.';
  END IF;
  IF nova_situacao NOT IN ('liberado', 'bloqueado') THEN
    RAISE EXCEPTION 'Situação de veículo inválida.';
  END IF;
  UPDATE public.veiculos SET situacao = nova_situacao WHERE codigo = codigo_veiculo;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Veículo não encontrado.';
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION alterar_situacao_veiculo(VARCHAR, VARCHAR) TO authenticated;

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE veiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspecoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE itens_inspecao ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON usuarios, veiculos, inspecoes, itens_inspecao TO authenticated;
GRANT INSERT ON veiculos, inspecoes, itens_inspecao TO authenticated;
GRANT UPDATE ON veiculos TO authenticated;

CREATE OR REPLACE FUNCTION public.usuario_atual_id()
RETURNS BIGINT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id_usuario
  FROM public.usuarios
  WHERE auth_uid = auth.uid()
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.usuario_atual_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.usuario_atual_id() TO authenticated;

CREATE OR REPLACE FUNCTION public.salvar_inspecao(
  p_codigo_veiculo VARCHAR,
  p_resultado VARCHAR,
  p_veiculo_bloqueado BOOLEAN,
  p_observacoes TEXT,
  p_itens JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  usuario_id BIGINT;
  veiculo_id BIGINT;
  inspecao_id BIGINT;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'É necessário entrar no sistema.';
  END IF;

  usuario_id := public.usuario_atual_id();
  IF usuario_id IS NULL THEN
    RAISE EXCEPTION 'Não existe perfil vinculado ao usuário autenticado.';
  END IF;

  IF p_resultado IS NULL OR p_resultado NOT IN ('regular', 'irregular', 'pendente') THEN
    RAISE EXCEPTION 'Resultado da inspeção inválido.';
  END IF;
  IF jsonb_typeof(COALESCE(p_itens, '[]'::JSONB)) <> 'array' THEN
    RAISE EXCEPTION 'A lista de itens da inspeção é inválida.';
  END IF;

  SELECT id_veiculo INTO veiculo_id
  FROM public.veiculos
  WHERE codigo = upper(btrim(p_codigo_veiculo));
  IF veiculo_id IS NULL THEN
    RAISE EXCEPTION 'Veículo não encontrado.';
  END IF;

  INSERT INTO public.inspecoes (
    id_veiculo, id_usuario, resultado, veiculo_bloqueado, observacoes
  ) VALUES (
    veiculo_id, usuario_id, p_resultado, COALESCE(p_veiculo_bloqueado, FALSE), p_observacoes
  ) RETURNING id_inspecao INTO inspecao_id;

  INSERT INTO public.itens_inspecao (
    id_inspecao, categoria, nome_item, valor, resultado, item_critico
  )
  SELECT
    inspecao_id,
    item ->> 'categoria',
    item ->> 'nome_item',
    NULLIF(item ->> 'valor', ''),
    item ->> 'resultado',
    COALESCE((item ->> 'item_critico')::BOOLEAN, FALSE)
  FROM jsonb_array_elements(COALESCE(p_itens, '[]'::JSONB)) AS item;

  UPDATE public.veiculos
  SET situacao = CASE
    WHEN COALESCE(p_veiculo_bloqueado, FALSE) THEN 'bloqueado'
    ELSE 'liberado'
  END
  WHERE id_veiculo = veiculo_id;

  RETURN inspecao_id;
END;
$$;

REVOKE ALL ON FUNCTION public.salvar_inspecao(VARCHAR, VARCHAR, BOOLEAN, TEXT, JSONB)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.salvar_inspecao(VARCHAR, VARCHAR, BOOLEAN, TEXT, JSONB)
  TO authenticated;

-- Permite ao autor corrigir uma inspeção somente nos dez minutos após a criação.
-- A data original não é alterada, portanto uma correção não renova o prazo.
CREATE OR REPLACE FUNCTION public.corrigir_inspecao(
  p_inspecao_id BIGINT,
  p_resultado VARCHAR,
  p_veiculo_bloqueado BOOLEAN,
  p_observacoes TEXT,
  p_itens JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  usuario_id BIGINT;
  veiculo_id BIGINT;
  autor_id BIGINT;
  criada_em TIMESTAMPTZ;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'É necessário entrar no sistema.';
  END IF;
  usuario_id := public.usuario_atual_id();
  IF usuario_id IS NULL THEN
    RAISE EXCEPTION 'Não existe perfil vinculado ao usuário autenticado.';
  END IF;
  IF p_resultado IS NULL OR p_resultado NOT IN ('regular', 'irregular', 'pendente') THEN
    RAISE EXCEPTION 'Resultado da inspeção inválido.';
  END IF;
  IF jsonb_typeof(COALESCE(p_itens, '[]'::JSONB)) <> 'array' THEN
    RAISE EXCEPTION 'A lista de itens da inspeção é inválida.';
  END IF;

  SELECT id_usuario, id_veiculo, data_da_inspecao
    INTO autor_id, veiculo_id, criada_em
  FROM public.inspecoes
  WHERE id_inspecao = p_inspecao_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Inspeção não encontrada.';
  END IF;
  IF autor_id <> usuario_id THEN
    RAISE EXCEPTION 'Somente o autor da inspeção pode corrigi-la.';
  END IF;
  IF clock_timestamp() > criada_em + INTERVAL '10 minutes' THEN
    RAISE EXCEPTION 'O prazo de correção de 10 minutos foi encerrado.';
  END IF;

  UPDATE public.inspecoes
  SET resultado = p_resultado,
      veiculo_bloqueado = COALESCE(p_veiculo_bloqueado, FALSE),
      observacoes = p_observacoes
  WHERE id_inspecao = p_inspecao_id;

  DELETE FROM public.itens_inspecao WHERE id_inspecao = p_inspecao_id;
  INSERT INTO public.itens_inspecao (
    id_inspecao, categoria, nome_item, valor, resultado, item_critico
  )
  SELECT
    p_inspecao_id,
    item ->> 'categoria',
    item ->> 'nome_item',
    NULLIF(item ->> 'valor', ''),
    item ->> 'resultado',
    COALESCE((item ->> 'item_critico')::BOOLEAN, FALSE)
  FROM jsonb_array_elements(COALESCE(p_itens, '[]'::JSONB)) AS item;

  UPDATE public.veiculos
  SET situacao = CASE
    WHEN COALESCE(p_veiculo_bloqueado, FALSE) THEN 'bloqueado'
    ELSE 'liberado'
  END
  WHERE id_veiculo = veiculo_id;
END;
$$;

REVOKE ALL ON FUNCTION public.corrigir_inspecao(BIGINT, VARCHAR, BOOLEAN, TEXT, JSONB)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.corrigir_inspecao(BIGINT, VARCHAR, BOOLEAN, TEXT, JSONB)
  TO authenticated;

DROP POLICY IF EXISTS usuarios_consultar_perfil ON usuarios;
CREATE POLICY usuarios_consultar_perfil ON usuarios
  FOR SELECT TO authenticated
  USING (TRUE);

DO $$
DECLARE
  politica RECORD;
BEGIN
  FOR politica IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'veiculos'
  LOOP
    EXECUTE format('DROP POLICY %I ON public.veiculos', politica.policyname);
  END LOOP;
END;
$$;

CREATE POLICY veiculos_consultar ON veiculos
  FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY veiculos_cadastrar_autenticado ON veiculos
  FOR INSERT TO authenticated WITH CHECK (TRUE);
CREATE POLICY veiculos_atualizar_autenticado ON veiculos
  FOR UPDATE TO authenticated USING (TRUE) WITH CHECK (TRUE);

DO $$
DECLARE
  politica RECORD;
BEGIN
  FOR politica IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public' AND tablename IN ('inspecoes', 'itens_inspecao')
  LOOP
    EXECUTE format(
      'DROP POLICY %I ON public.%I',
      politica.policyname,
      politica.tablename
    );
  END LOOP;
END;
$$;

CREATE POLICY inspecoes_consultar ON inspecoes
  FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY inspecoes_cadastrar ON inspecoes
  FOR INSERT TO authenticated
  WITH CHECK (id_usuario = public.usuario_atual_id());

CREATE POLICY itens_consultar ON itens_inspecao
  FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY itens_cadastrar ON itens_inspecao
  FOR INSERT TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.inspecoes
      WHERE inspecoes.id_inspecao = itens_inspecao.id_inspecao
        AND inspecoes.id_usuario = public.usuario_atual_id()
    )
  );

INSERT INTO veiculos
  (codigo, nome_modelo, placa, pressao_minima_psi, pressao_maxima_psi)
VALUES
  ('001', 'Caminhão 1', 'ABC1234', 30, 38),
  ('002', 'Caminhão 2', 'XYZ9876', 28, 36),
  ('003', 'Van de logística', 'LMN4567', 31, 35)
ON CONFLICT (codigo) DO UPDATE SET
  nome_modelo = EXCLUDED.nome_modelo,
  placa = EXCLUDED.placa,
  pressao_minima_psi = EXCLUDED.pressao_minima_psi,
  pressao_maxima_psi = EXCLUDED.pressao_maxima_psi;
